INSERT INTO roles (title, status, created_at, updated_at) VALUES
('Admin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Manager', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Customer', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vendor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Staff', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
